{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dasher.fullname" . }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "dasher.fullname" . }}
            port:
              name: web
        pathType: Prefix
{{- end -}}