{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dasher-chart.fullname" . }}  # Corrected indentation
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: dasher-server-service
            port:
              name: web
        pathType: Prefix
{{- end -}}