{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dasher.fullname" . }}
spec:
  {{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq .Values.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    app: dasher-server
  ports:
    - name: web
      port: 3000
      protocol: TCP
    - name: grpc
      port: 50051
      protocol: TCP
{{- end -}}