// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Feature struct {
	FeatureID   string
	Description sql.NullString
	Enabled     sql.NullInt64
}
