// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: pkg/proto/feature.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureToggle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeatureId   string `protobuf:"bytes,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *FeatureToggle) Reset() {
	*x = FeatureToggle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_feature_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureToggle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureToggle) ProtoMessage() {}

func (x *FeatureToggle) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_feature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureToggle.ProtoReflect.Descriptor instead.
func (*FeatureToggle) Descriptor() ([]byte, []int) {
	return file_pkg_proto_feature_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureToggle) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *FeatureToggle) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Main message for feature toggle states
type FeatureToggleChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeatureId string `protobuf:"bytes,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Enabled   bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *FeatureToggleChange) Reset() {
	*x = FeatureToggleChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_feature_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureToggleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureToggleChange) ProtoMessage() {}

func (x *FeatureToggleChange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_feature_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureToggleChange.ProtoReflect.Descriptor instead.
func (*FeatureToggleChange) Descriptor() ([]byte, []int) {
	return file_pkg_proto_feature_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureToggleChange) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *FeatureToggleChange) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// Empty message for subscription request
type FeatureSubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeatureToggles []*FeatureToggle `protobuf:"bytes,1,rep,name=featureToggles,proto3" json:"featureToggles,omitempty"`
}

func (x *FeatureSubscription) Reset() {
	*x = FeatureSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_feature_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSubscription) ProtoMessage() {}

func (x *FeatureSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_feature_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSubscription.ProtoReflect.Descriptor instead.
func (*FeatureSubscription) Descriptor() ([]byte, []int) {
	return file_pkg_proto_feature_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureSubscription) GetFeatureToggles() []*FeatureToggle {
	if x != nil {
		return x.FeatureToggles
	}
	return nil
}

var File_pkg_proto_feature_proto protoreflect.FileDescriptor

var file_pkg_proto_feature_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x22, 0x50, 0x0a, 0x0d, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x13, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x22, 0x55, 0x0a, 0x13, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0e, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x0e, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x73, 0x32, 0x6e, 0x0a, 0x13, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x57, 0x0a, 0x17, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x2e,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x2e, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x30, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x6f, 0x68, 0x61, 0x6e,
	0x73, 0x65, 0x6e, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_feature_proto_rawDescOnce sync.Once
	file_pkg_proto_feature_proto_rawDescData = file_pkg_proto_feature_proto_rawDesc
)

func file_pkg_proto_feature_proto_rawDescGZIP() []byte {
	file_pkg_proto_feature_proto_rawDescOnce.Do(func() {
		file_pkg_proto_feature_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_feature_proto_rawDescData)
	})
	return file_pkg_proto_feature_proto_rawDescData
}

var file_pkg_proto_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_feature_proto_goTypes = []any{
	(*FeatureToggle)(nil),       // 0: feature.FeatureToggle
	(*FeatureToggleChange)(nil), // 1: feature.FeatureToggleChange
	(*FeatureSubscription)(nil), // 2: feature.FeatureSubscription
}
var file_pkg_proto_feature_proto_depIdxs = []int32{
	0, // 0: feature.FeatureSubscription.featureToggles:type_name -> feature.FeatureToggle
	2, // 1: feature.FeatureStateService.SubscribeFeatureChanges:input_type -> feature.FeatureSubscription
	1, // 2: feature.FeatureStateService.SubscribeFeatureChanges:output_type -> feature.FeatureToggleChange
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_feature_proto_init() }
func file_pkg_proto_feature_proto_init() {
	if File_pkg_proto_feature_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_feature_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FeatureToggle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_feature_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FeatureToggleChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_feature_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FeatureSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_feature_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_feature_proto_goTypes,
		DependencyIndexes: file_pkg_proto_feature_proto_depIdxs,
		MessageInfos:      file_pkg_proto_feature_proto_msgTypes,
	}.Build()
	File_pkg_proto_feature_proto = out.File
	file_pkg_proto_feature_proto_rawDesc = nil
	file_pkg_proto_feature_proto_goTypes = nil
	file_pkg_proto_feature_proto_depIdxs = nil
}
