name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_REPO: dasher-server

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Go test
      run: go test ./... -race

  docker:
    needs: test
    runs-on: ubuntu-latest
    name: Deliver to Docker Hub
    steps:
    - name: Login to Docker Hub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    
    - name: Docker build
      run: |
        docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest -f build/server.dockerfile .

    - name: Docker push
      run: |
        docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest